const { chromium } = require('playwright');
const path = require('path');
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1440, height: 950 } });
  const errs = [];
  p.on('pageerror', e => errs.push('PE ' + e.message));
  p.on('console', m => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) errs.push(m.text()); });
  await p.route('**/*', r => (r.request().url().startsWith('file:') ? r.continue() : r.abort()));
  await p.goto('file://' + path.resolve('dist-single/index.html'));
  await p.waitForTimeout(600);
  await p.screenshot({ path: 'e2e/01-inicio.png' });
  for (let k = 0; k < 5; k++) await p.click('.marca h1'); // modo profesor (5 clics en el título)
  await p.click('.mapa li:nth-child(3) .nodo');
  await p.waitForTimeout(300);
  const ghost = () => p.evaluate(() => document.querySelector('.cm-ghost')?.textContent ?? null);
  await p.click('.cm-content');
  await p.keyboard.press('Control+End'); await p.keyboard.press('ArrowUp'); await p.keyboard.press('ArrowUp'); await p.keyboard.press('End');
  await p.keyboard.press('Enter'); await p.keyboard.press('Enter');
  await p.keyboard.type('public Robot(String nombre, String color', { delay: 15 });
  await p.keyboard.type(')');
  await p.waitForTimeout(250);
  console.log('ghost header:', JSON.stringify(await ghost()));
  await p.keyboard.press('Tab'); await p.keyboard.press('Enter'); await p.waitForTimeout(250);
  console.log('ghost ctor 1:', JSON.stringify(await ghost()));
  await p.keyboard.press('Tab'); await p.keyboard.press('Enter'); await p.waitForTimeout(250);
  console.log('ghost ctor 2:', JSON.stringify(await ghost()));
  await p.keyboard.press('Tab'); await p.keyboard.press('Enter');
  await p.keyboard.type('this.en', { delay: 30 }); await p.waitForTimeout(300);
  console.log('autocompletado:', await p.evaluate(() => [...document.querySelectorAll('.cm-tooltip-autocomplete li')].map(l => l.textContent)));
  await p.keyboard.press('Enter');
  await p.keyboard.type(' = 100', { delay: 20 }); await p.waitForTimeout(250);
  console.log('ghost ;:', JSON.stringify(await ghost()));
  await p.keyboard.press('Tab');
  const doc = await p.evaluate(() => document.querySelector('.cm-content').innerText);
  console.log(doc);
  await p.click('.btn-pri'); await p.waitForTimeout(400);
  console.log('veredicto:', await p.textContent('.veredicto'));
  await p.screenshot({ path: 'e2e/02-enviado.png' });
  await p.waitForTimeout(1800);
  console.log('modal:', await p.evaluate(() => document.querySelector('.modal h2')?.textContent));
  await p.screenshot({ path: 'e2e/03-modal.png' });
  // Nivel 4: sugerencias en Main
  await p.click('.modal .btn-pri'); await p.waitForTimeout(300);
  console.log('archivo activo:', await p.textContent('.archivo[aria-selected="true"]'));
  await p.click('.cm-content');
  await p.keyboard.press('Control+End'); for (let k = 0; k < 3; k++) await p.keyboard.press('ArrowUp'); await p.keyboard.press('End');
  await p.keyboard.type('Robot ', { delay: 20 }); await p.waitForTimeout(250);
  console.log('ghost Robot:', JSON.stringify(await ghost()));
  await p.keyboard.press('Tab'); await p.keyboard.type('Tornillo', { delay: 10 }); await p.waitForTimeout(200);
  console.log('firma:', await p.evaluate(() => document.querySelector('.cm-firma')?.textContent ?? null));
  await p.keyboard.press('End'); await p.keyboard.press('Enter');
  await p.keyboard.type('sout'); await p.keyboard.press('Escape'); await p.keyboard.press('Tab');
  await p.keyboard.type('robot.', { delay: 30 }); await p.waitForTimeout(300);
  console.log('miembros:', await p.evaluate(() => [...document.querySelectorAll('.cm-tooltip-autocomplete li')].map(l => l.textContent)));
  await p.keyboard.press('Escape');
  await p.keyboard.press('End');
  await p.keyboard.press('Enter'); await p.keyboard.type('if (robot.nombre = "x") robot.avanzar();', { delay: 3 });
  await p.waitForTimeout(900);
  console.log('lens:', await p.evaluate(() => [...document.querySelectorAll('.cm-lens')].map(x => x.textContent)));
  await p.click('.btn-sec >> text=Ejecutar código'); await p.waitForTimeout(300);
  console.log('veredicto 4:', await p.textContent('.veredicto'));
  await p.screenshot({ path: 'e2e/04-errores.png' });
  // Jefe con la solución
  await p.click('.mapa li:nth-child(6) .nodo'); await p.waitForTimeout(200);
  await p.click('text=Mostrar la respuesta'); await p.click('text=Reemplazar'); await p.waitForTimeout(200);
  await p.click('.btn-pri'); await p.waitForTimeout(2500);
  await p.screenshot({ path: 'e2e/05-jefe.png' });
  console.log('veredicto jefe:', await p.textContent('.veredicto'));
  console.log('errores:', errs);
  await b.close();
})();
